 const chartsImagesPaths = {
    Pie: '/static/images/piechart.svg',
    Table: '/static/images/table.svg',
    Column: '/static/images/columngraph.svg',
    Stacked_Column: '/static/images/stackedcolumn.svg',
    Area: '/static/images/area.svg',
    Dual_Axis: '/static/images/dualaxischart.svg',
    Line: '/static/images/linegraph.svg',
    Single_Metric: '/static/images/number.svg',
    USA_Map: '/static/images/map.svg',
    Bar: '/static/images/barchart.svg',
    Bell_Curve: '/static/images/bellcurve.svg',
    Packed_Bubble: '/static/images/bubblechart.svg',
    Dumbell: '/static/images/dumbellchart.svg',
    Funnel: '/static/images/funnelchart.svg',
    Heat_Map: '/static/images/heatmap.svg',
    Histogram: '/static/images/histogram.svg',
    Sankey_Diagram: '/static/images/sankeydiagram.svg',
    Scatter_Plot: '/static/images/scatterchart.svg',
    Steam_Graph: '/static/images/steamgraph.svg',
    Word_Cloud: '/static/images/wordcloud.svg',
    Tile_Map: '/static/images/tilemap.svg',
    Tree_Map: '/static/images/treemap.svg',
    Water_Fall: '/static/images/waterfallchart.svg',
    Area_Spline: '/static/images/areasplice.svg',
    Number: '/static/images/numbers.svg',
    Stacked_Bar: '/static/images/stackedbar.svg',
    World_Map: '/static/images/worldmap.svg'
  }
  export default chartsImagesPaths;